model_name_or_path: models/Qwen/Qwen3-1___7B
stage: sft
do_train: true
finetuning_type: lora
lora_target: all

output_dir: output/qwen3_dbt_lora
overwrite_output_dir: true

dataset: dbt_counseling
dataset_dir: datasets
template: qwen
cutoff_len: 1024
preprocessing_num_workers: 1

per_device_train_batch_size: 1
gradient_accumulation_steps: 8
lr_scheduler_type: cosine
logging_steps: 10
save_steps: 500
learning_rate: 5.0e-5
num_train_epochs: 3.0
max_grad_norm: 1.0
fp16: true

lora_rank: 8
lora_alpha: 16
lora_dropout: 0.1

warmup_ratio: 0.1
report_to: none
